/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/babel-es6-es5': RouteRecordInfo<'/posts/babel-es6-es5', '/posts/babel-es6-es5', Record<never, never>, Record<never, never>>,
    '/posts/cfw-tun': RouteRecordInfo<'/posts/cfw-tun', '/posts/cfw-tun', Record<never, never>, Record<never, never>>,
    '/posts/css-10-tricks': RouteRecordInfo<'/posts/css-10-tricks', '/posts/css-10-tricks', Record<never, never>, Record<never, never>>,
    '/posts/css-font': RouteRecordInfo<'/posts/css-font', '/posts/css-font', Record<never, never>, Record<never, never>>,
    '/posts/css-name': RouteRecordInfo<'/posts/css-name', '/posts/css-name', Record<never, never>, Record<never, never>>,
    '/posts/css-norm': RouteRecordInfo<'/posts/css-norm', '/posts/css-norm', Record<never, never>, Record<never, never>>,
    '/posts/docker-registry': RouteRecordInfo<'/posts/docker-registry', '/posts/docker-registry', Record<never, never>, Record<never, never>>,
    '/posts/git-basic-tutorial': RouteRecordInfo<'/posts/git-basic-tutorial', '/posts/git-basic-tutorial', Record<never, never>, Record<never, never>>,
    '/posts/git-learn-note': RouteRecordInfo<'/posts/git-learn-note', '/posts/git-learn-note', Record<never, never>, Record<never, never>>,
    '/posts/git-listing': RouteRecordInfo<'/posts/git-listing', '/posts/git-listing', Record<never, never>, Record<never, never>>,
    '/posts/git-npm-proxy': RouteRecordInfo<'/posts/git-npm-proxy', '/posts/git-npm-proxy', Record<never, never>, Record<never, never>>,
    '/posts/jdcookie': RouteRecordInfo<'/posts/jdcookie', '/posts/jdcookie', Record<never, never>, Record<never, never>>,
    '/posts/js-copy-clipboard-api': RouteRecordInfo<'/posts/js-copy-clipboard-api', '/posts/js-copy-clipboard-api', Record<never, never>, Record<never, never>>,
    '/posts/js-echarts': RouteRecordInfo<'/posts/js-echarts', '/posts/js-echarts', Record<never, never>, Record<never, never>>,
    '/posts/js-ismobile': RouteRecordInfo<'/posts/js-ismobile', '/posts/js-ismobile', Record<never, never>, Record<never, never>>,
    '/posts/js-nocopy': RouteRecordInfo<'/posts/js-nocopy', '/posts/js-nocopy', Record<never, never>, Record<never, never>>,
    '/posts/js-skills': RouteRecordInfo<'/posts/js-skills', '/posts/js-skills', Record<never, never>, Record<never, never>>,
    '/posts/js-this-principle': RouteRecordInfo<'/posts/js-this-principle', '/posts/js-this-principle', Record<never, never>, Record<never, never>>,
    '/posts/markdown-basic-syntax': RouteRecordInfo<'/posts/markdown-basic-syntax', '/posts/markdown-basic-syntax', Record<never, never>, Record<never, never>>,
    '/posts/prettierrc-config': RouteRecordInfo<'/posts/prettierrc-config', '/posts/prettierrc-config', Record<never, never>, Record<never, never>>,
    '/posts/proxy-tools': RouteRecordInfo<'/posts/proxy-tools', '/posts/proxy-tools', Record<never, never>, Record<never, never>>,
    '/posts/proxy-v2ray': RouteRecordInfo<'/posts/proxy-v2ray', '/posts/proxy-v2ray', Record<never, never>, Record<never, never>>,
    '/posts/ql-jd': RouteRecordInfo<'/posts/ql-jd', '/posts/ql-jd', Record<never, never>, Record<never, never>>,
    '/posts/web-commom-words': RouteRecordInfo<'/posts/web-commom-words', '/posts/web-commom-words', Record<never, never>, Record<never, never>>,
    '/posts/web-norm': RouteRecordInfo<'/posts/web-norm', '/posts/web-norm', Record<never, never>, Record<never, never>>,
    '/resume/': RouteRecordInfo<'/resume/', '/resume', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
